### ISSUE TITLE
Ubuntu Jammy

### ISSUE THREAD

**Issue by fmorillo** [haproxytech/haproxy-docker-ubuntu#6]
Hi,

I was wondering when the switch to the ubuntu jammy base image is going to happen. I just tested haproxy2.7-dev4 with openssl3 and lua5.4 and that worked perfectly. I'm interested in that because lua5.4 is only in the package repos for jammy and it is quite a bit faster than its predecessor https://lwn.net/Articles/826136/ .

Best Regards

**Comment by dkorunic** [comment]
Main trouble with Ubuntu 22.04 (Jammy Jellyfish) is that it ships with OpenSSL 3.0 which is known to have performance regressions and from our experience the performance will not match OpenSSL 1.1 branch. So the root cause why we are not upgrading our Ubuntu containers is because of disappointing performance so far.

**Comment by dkorunic** [comment]
Completed in https://github.com/haproxytech/haproxy-docker-ubuntu/commit/a2573f338087cd0106cb9caff4ea86ffca35ea4a.
